# Generated by Django 3.2.10 on 2022-01-02 23:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Altor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=100)),
                ('sobre_nome', models.CharField(max_length=100)),
                ('data_de_nascimento', models.DateField(blank=True, null=True)),
                ('data_da_morte', models.DateField(blank=True, null=True, verbose_name='Faleceu')),
            ],
            options={
                'ordering': ['sobre_nome', 'primeiro_nome'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o gênero de um livro (por exemplo, ficção científica)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField(help_text='Insira uma breve descrição do livro', max_length=1000)),
                ('isbn', models.CharField(help_text='13 Personagem <a href="https://www.cblservicos.org.br/isbn/">número ISBN</a>', max_length=13, verbose_name='ISBN')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.altor')),
                ('genero', models.ManyToManyField(help_text='Selecione um gênero para este livro', to='catalogo.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaDoLivro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID exclusivo para este livro específico em toda a biblioteca', primary_key=True, serialize=False)),
                ('imprimir', models.CharField(max_length=200)),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Manutenção'), ('p', 'Por empréstimo'), ('d', 'Disponível'), ('r', 'Reservado')], default='m', help_text='Disponibilidade dos livros', max_length=1)),
                ('livro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.livro')),
            ],
            options={
                'ordering': ['data_retorno'],
            },
        ),
    ]
