# Generated by Django 3.2 on 2022-01-03 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20220102_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='altor',
            options={'ordering': ['sobre_nome', 'primeiro_nome'], 'verbose_name': 'Altor', 'verbose_name_plural': 'Altores'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterModelOptions(
            name='instanciadolivro',
            options={'ordering': ['data_retorno'], 'verbose_name': 'Instancia Do Livro', 'verbose_name_plural': 'Instancia Dos Livros'},
        ),
        migrations.AlterModelOptions(
            name='linguagem',
            options={'verbose_name': 'Linguagem', 'verbose_name_plural': 'Linguagens'},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.RenameField(
            model_name='instanciadolivro',
            old_name='imprimir',
            new_name='publicado',
        ),
    ]
