# Generated by Django 3.2 on 2022-01-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20220103_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='fotoLivro',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%d/%m/%Y', verbose_name='Foto do Livro'),
        ),
    ]
