# Generated by Django 3.2 on 2022-01-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_livro_fotolivro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='fotoLivro',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d', verbose_name='Foto do Livro'),
        ),
    ]
