# Generated by Django 3.2 on 2022-01-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_livro_fotolivro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='fotoLivro',
            new_name='foto',
        ),
    ]
